blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://stellar.stackexchange.com/questions/ask
    about: Please ask questions here
  - name: Developer Mailing List
    url: https://groups.google.com/g/stellar-dev
    about: Discuss Core Advancement Proposals (CAPs) and Stellar Ecosystem Proposals (SEPs) and talk about development of stellar-core, Horizon, and the rest of the Stellar platform. A place for conversations that move the protocol and ecosystem forward.
  - name: Protocol requests
    url: https://github.com/stellar/stellar-protocol
    about: Propose changes to the Stellar protocol (CAPs) or ecosystem (SEPs) standards
