blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://stellar.stackexchange.com/questions/ask
    about: Please ask questions here
  - name: Protocol requests
    url: https://github.com/stellar/stellar-protocol
    about: Propose changes to the Stellar protocol or ecosystem standards
